#!/usr/bin/sh

bat=/sys/class/power_supply/BAT1/
stat="$(cat "$bat/status")"
prcnt="$(cat "$bat/capacity" | tr -cd '[[:digit:]]')"

nocharge() {
if (( $prcnt == 100 )); then
	echo "󰁹"
elif (( $prcnt > 89 )); then
	echo "󰂂"
elif (( $prcnt > 79 )); then
	echo "󰂀"
elif (( $prcnt > 49 )); then
	echo "󰁿"
elif (( $prcnt > 29 )); then
	echo "󰁼"
elif (( $prcnt > 19 )) || (( $prcnt == 19 )) ; then
	echo "󰁻"
elif (( $prcnt < 19 )); then
	echo "󰂃"
fi
}

charge() {
if (( $prcnt == 100 )); then
	echo "󰂅"
elif (( $prcnt > 89 )); then
	echo "󰂋"
elif (( $prcnt > 79 )); then
	echo "󰂊"
elif (( $prcnt > 59 )); then
	echo "󰂉"
elif (( $prcnt > 39 )); then
	echo "󰂈"
elif (( $prcnt > 19 )) || (( $prcnt == 19 )); then
	echo "󰂇"
elif (( $prcnt < 19 )); then
	echo "󰂆"
fi
}

battprcnt() {
	echo "$prcnt%"
}

[ "$1" == "battstatus" ] && [ "$stat" == "Charging" ] && charge && exit
[ "$1" == "battstatus" ] && [ "$stat" == "Discharging" ] && nocharge && exit
[ "$1" == "battstatus" ] && [ "$stat" == "Not charging" ] && nocharge && exit
[ "$1" == "battprcnt" ] && battprcnt && exit
