#!/usr/bin/sh

bat=/sys/class/power_supply/BAT1/
stat="$(cat "$bat/status")"
prcnt="$(cat /sys/class/power_supply/BAT1/capacity | tr -cd '[[:digit:]]' | sed '/%d/g')"

nocharge() {
if [[ $prcnt == 100 ]]; then
	echo "󰁹"
elif [[ $prcnt > 90 ]]; then
	echo "󰂂"
elif [[ $prcnt > 80 ]]; then
	echo "󰂀"
elif [[ $prcnt > 60 ]]; then
	echo "󰁿"
elif [[ $prcnt > 60 ]]; then
	echo "󰁿"
elif [[ $prcnt > 40 ]]; then
	echo "󰁻"
elif [[ $prcnt > 9 ]]; then
	echo "󰁻"
elif [[ $prcnt < 9 ]]; then
	echo "󰂃"
fi
}

charge() {
if [[ $prcnt == 100 ]]; then
	echo "󰂅"
elif [[ $prcnt > 79 ]]; then
	echo "󰂋"
elif [[ $prcnt > 59 ]]; then
	echo "󰂊"
elif [[ $prcnt > 49 ]]; then
	echo "󰂊"
elif [[ $prcnt > 39 ]]; then
	echo "󰂈"
elif [[ $prcnt > 29 ]]; then
	echo "󰂈"
elif [[ $prcnt > 9 ]]; then
	echo "󰂈"
elif [[ $prcnt < 9 ]]; then
	echo "󰂆"
fi
}

battprcnt() {
	echo "$prcnt%"
}

if [ "$1" == "battstatus" ] && [ "$stat" == "Charging" ]; then
	charge
elif [ "$1" == "battstatus" ] && [ "$stat" == "Discharging" ]; then
	nocharge
elif [ "$1" == "battstatus" ] && [ "$stat" == "Not charging" ]; then
	nocharge
elif [ "$1" == "battprcnt" ]; then
	battprcnt
fi
