#!/usr/bin/sh

bat=/sys/class/power_supply/BAT1/
stat="$(cat "$bat/status")"
prcnt="$(cat "$bat/capacity")"

nocharge() {
if [[ $prcnt == 100 ]]; then
	echo "󰁹"
elif [[ $prcnt > 79 ]]; then
	echo "󰂂"
elif [[ $prcnt > 69 ]]; then
	echo "󰂁"
elif [[ $prcnt > 59 ]]; then
	echo "󰂀"
elif [[ $prcnt > 49 ]]; then
	echo "󰁿"
elif [[ $prcnt > 39 ]]; then
	echo "󰁿"
elif [[ $prcnt > 29 ]]; then
	echo "󰁿"
elif [[ $prcnt > 19 ]]; then
	echo "$(notify-send -t 5000 'BATTERY LOW' 'Please Plug Your AC Adapter')"
	echo "󰁻"
elif [[ $prcnt > 9 ]]; then
	echo "$(notify-send -t 5000 'BATTERY CRITICAL' 'Please Plug Your AC Adapter Immidiately')"
	echo "󰂃"
fi
}

charge() {
if [[ $prcnt == 100 ]]; then
	echo "󰂅"
elif [[ $prcnt > 89 ]]; then
	echo "󰂋"
elif [[ $prcnt > 79 ]]; then
	echo "󰂊"
elif [[ $prcnt > 59 ]]; then
	echo "󰂊"
elif [[ $prcnt > 49 ]]; then
	echo "󰂉"
elif [[ $prcnt > 39 ]]; then
	echo "󰂉"
elif [[ $prcnt > 19 ]]; then
	echo "󰂈"
elif [[ $prcnt > 9 ]]; then
	echo "󰂆"
elif [[ $prcnt > 0 ]]; then
	echo "󰂆"
fi
}

battprcnt() {
	echo "$prcnt%"
}

if [ "$1" == "battstatus" ] && [ $stat == "Charging" ]; then
	charge
elif [ "$1" == "battstatus" ] && [ $stat == "Discharging" ]; then
	nocharge
elif [ "$1" == "battstatus" ] && [ $stat == "Not charging" ]; then
	nocharge
elif [ "$1" == "battprcnt" ]; then
	battprcnt
fi
