#!/usr/bin/sh

prnt="$(xbacklight -getf | awk -F"." '{print $1}' )"

if (( $prnt > 70 )); then
	echo "󱩖 $prnt%"
elif (( $prnt > 40 )); then
	echo "󱩔 $prnt%"
elif (( $prnt > 20 )); then
	echo "󱩓 $prnt%"
elif (( $prnt > 10 )) || (( $prnt == 10 )); then
	echo "󱩐 $prnt%"
elif (( $prnt < 10 )); then
	echo "󱧢 $prnt%"
fi
