#!/usr/bin/sh

vol="$(amixer sget Master | awk -F"[][]" '/Right:/ {print $2}')"

if [[ $vol == "100%" ]]; then
	echo " $vol"
elif [[ $vol > "50%" ]]; then
	echo " $vol"
elif [[ $vol > "20%" ]]; then
	echo " $vol"
elif [[ "$vol" < "21%" ]]; then
	echo " $vol"
fi
