#!/usr/bin/sh

stat="$(nmcli device status | grep "wlan0" | awk 'FNR==1 {print $3}')"
ssid="$(nmcli -f ACTIVE,SSID device wifi | grep "yes" | awk -F" " '{print $2, $3, $4}')"
str="$(nmcli -f ACTIVE,SIGNAL device wifi | grep "yes" | tr -cd '[[:digit:]]')"

if [[ $stat == "connected" ]] && [[ $str > 79 ]]; then
	echo "󰤨 Connected to $ssid"
elif [[ $stat == "connected" ]] && [[ $str > 59 ]]; then
	echo "󰤥 Connected to $ssid"
elif [[ $stat == "connected" ]] && [[ $str > 39 ]]; then
	echo "󰤢 Connected to $ssid"
elif [[ $stat == "connected" ]] && [[ $str < 39 ]]; then
	echo "󰤟 Connected to $ssid"
elif [[ $stat == "disconnected" ]]; then
	echo "󰤮 Disconnected"
fi
