#!/usr/bin/sh

wifi="$(nmcli -f ACTIVE,SSID device wifi | grep "yes" | cut -d " " -f1)"
ssid="$(nmcli -f ACTIVE,SSID device wifi | grep "yes" | cut -b 9-)"

status() {
if [[ $wifi == "yes" ]]; then
	echo "󰖩 Connected to"
else
	echo "󰖪 Disconnected"
fi
}

name() {
echo $ssid
}

[ "$1" == "status" ] && status && exit
[ "$1" == "name" ] && name && exit
