#!/usr/bin/sh

ssid="$(nmcli -t -f SSID device wifi | awk 'NR==1 {print NR,$0}' | cut -d " " -f2)"
stat="$(nmcli -t -f ACTIVE device wifi | awk 'NR==1 {print NR,$0}' | cut -d " " -f2)"

if [[ $stat == yes ]]; then
	echo "$ssid"
else
	echo ""
fi
